<a href="https://colab.research.google.com/github/irenydsilva/DesafioPython1/blob/main/Projeto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Passo 1: Importar a base de dados do excel**

In [1]:
import pandas as pd


tabela_vendas = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx")

display(tabela_vendas)

        Código Venda       Data  ... Valor Unitário Valor Final
0                  1 2019-01-01  ...            358         358
1                  1 2019-01-01  ...            180         360
2                  1 2019-01-01  ...            368         368
3                  2 2019-01-02  ...            200         600
4                  2 2019-01-02  ...             71          71
...              ...        ...  ...            ...         ...
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[100999 rows x 7 columns]

**Passo 2: Calcular o faturamento de cada loja**

In [2]:
tabela_faturamento = tabela_vendas[["ID Loja", "Valor Final"]]

display(tabela_faturamento)

                           ID Loja  Valor Final
0               Iguatemi Esplanada          358
1               Iguatemi Esplanada          360
2               Iguatemi Esplanada          368
3                   Norte Shopping          600
4                   Norte Shopping           71
...                            ...          ...
100994  Center Shopping Uberlândia          204
100995  Center Shopping Uberlândia         1080
100996  Center Shopping Uberlândia           87
100997           Ribeirão Shopping          108
100998           Ribeirão Shopping          266

[100999 rows x 2 columns]

*agrupando por loja, soma de cada loja em ordem crescente*

In [4]:
tabela_faturamento = tabela_vendas[["ID Loja", "Valor Final"]].groupby("ID Loja").sum()
tabela_faturamento = tabela_faturamento.sort_values(by="Valor Final", ascending=False)

display(tabela_faturamento)

                                  Valor Final
ID Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

**Passo 3: Calcular a quantidade de produtos vendidos em cada loja**

In [9]:
tabela_quantidade = tabela_vendas[["ID Loja","Quantidade"]].groupby("ID Loja").sum()
tabela_quantidade = tabela_quantidade.sort_values(by="Quantidade", ascending=False)

display(tabela_quantidade)

                                  Quantidade
ID Loja
Shopping Vila Velha                     9224
Palladium Shopping Curitiba             9091
Norte Shopping                          9014
Shopping Center Leste Aricanduva        8938
Rio Mar Shopping Fortaleza              8937
Iguatemi Campinas                       8935
Shopping SP Market                      8927
Rio Mar Recife                          8863
Bourbon Shopping SP                     8863
Ribeirão Shopping                       8825
Novo Shopping Ribeirão Preto            8751
Shopping União de Osasco                8730
Shopping Ibirapuera                     8723
Shopping Eldorado                       8719
Salvador Shopping                       8698
Shopping Center Interlagos              8675
Shopping Barra                          8638
Shopping Iguatemi Fortaleza             8629
Center Shopping Uberlândia              8627
Passei das Águas Shopping               8618
Shopping Recife                         8581
Iguatemi Esplanada                      8580
Shopping Morumbi                        8508
Parque Dom Pedro Shopping               8388
Shopping Midway Mall                    8206

**Passo 4: Calcular o ticket médio**

*faturamento / quantidade*

In [12]:
ticket_medio = (tabela_faturamento["Valor Final"] / tabela_quantidade["Quantidade"]).to_frame()
ticket_medio = ticket_medio.rename(columns={0:"Ticket Medio"})
display(ticket_medio)

                                  Ticket Medio
ID Loja
Bourbon Shopping SP                 194.754598
Center Shopping Uberlândia          193.453228
Iguatemi Campinas                   197.248909
Iguatemi Esplanada                  198.098019
Norte Shopping                      189.923231
Novo Shopping Ribeirão Preto        191.775226
Palladium Shopping Curitiba         189.321307
Parque Dom Pedro Shopping           194.519552
Passei das Águas Shopping           191.345324
Ribeirão Shopping                   193.441586
Rio Mar Recife                      194.377299
Rio Mar Shopping Fortaleza          190.044758
Salvador Shopping                   189.323868
Shopping Barra                      191.375666
Shopping Center Interlagos          189.105014
Shopping Center Leste Aricanduva    188.282614
Shopping Eldorado                   189.025232
Shopping Ibirapuera                 187.442394
Shopping Iguatemi Fortaleza         194.092479
Shopping Midway Mall                193.814404
Shopping Morumbi                    186.464974
Shopping Recife                     189.357767
Shopping SP Market                  192.871401
Shopping União de Osasco            190.580756
Shopping Vila Velha                 187.680724

**Passo 5: Enviar email**

In [ ]:
def enviar_email(nome_da_loja, tabela):
  import smtplib
  import email.message

  server = smtplib.SMTP('smtp.gmail.com:587')  
  # ***** Corpo do E-mail #
  corpo_email = 
    f""" 
    <p>Prezados, </p>
    <p>Segue relatório de vendas</p>
    {tabela.to_html()}
    """
    
  msg = email.message.Message()
  msg['Subject'] = "Assunto do E-mail" # *****#
    
  # Fazer antes (apenas na 1ª vez): Ativar Aplicativos não Seguros.
    # Gerenciar Conta Google -> Segurança -> Aplicativos não Seguros -> Habilitar
  # Caso mesmo assim dê o erro: smtplib.SMTPAuthenticationError: (534,
  # Você faz o login no seu e-mail e depois entra em: https://accounts.google.com/DisplayUnlockCaptcha
  msg['From'] = 'remetente@gmail.com'   # **** #
  msg['To'] = 'destinatario@gmail.com'  # **** #
  password = "senha"  # **** #
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(corpo_email )
    
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

In [15]:
tabela_completa = tabela_faturamento.join(tabela_quantidade).join(ticket_medio)
display(tabela_completa)

                                  Valor Final  Quantidade  Ticket Medio
ID Loja
Iguatemi Campinas                     1762419        8935    197.248909
Shopping Vila Velha                   1731167        9224    187.680724
Bourbon Shopping SP                   1726110        8863    194.754598
Rio Mar Recife                        1722766        8863    194.377299
Shopping SP Market                    1721763        8927    192.871401
Palladium Shopping Curitiba           1721120        9091    189.321307
Norte Shopping                        1711968        9014    189.923231
Ribeirão Shopping                     1707122        8825    193.441586
Iguatemi Esplanada                    1699681        8580    198.098019
Rio Mar Shopping Fortaleza            1698430        8937    190.044758
Shopping Center Leste Aricanduva      1682870        8938    188.282614
Novo Shopping Ribeirão Preto          1678225        8751    191.775226
Shopping Iguatemi Fortaleza           1674824        8629    194.092479
Center Shopping Uberlândia            1668921        8627    193.453228
Shopping União de Osasco              1663770        8730    190.580756
Shopping Barra                        1653103        8638    191.375666
Passei das Águas Shopping             1649014        8618    191.345324
Shopping Eldorado                     1648111        8719    189.025232
Salvador Shopping                     1646739        8698    189.323868
Shopping Center Interlagos            1640486        8675    189.105014
Shopping Ibirapuera                   1635060        8723    187.442394
Parque Dom Pedro Shopping             1631630        8388    194.519552
Shopping Recife                       1624879        8581    189.357767
Shopping Midway Mall                  1590441        8206    193.814404
Shopping Morumbi                      1586444        8508    186.464974

In [ ]:
enviar_email("Diretoria", tabela_completa)

**Passo 6: Enviar email para uma loja de cada vez, sem o for**

In [17]:
loja= "Rio Mar Recife"

#linhas = sao as linhas onde na coluna ID Loja está escrito Rio Mar Recife

#linhas = tabela_vendas["ID Loja"] == loja
# colunas = ["ID Loja", "Quantidade", "Valor Final"]

# tabela_loja = tabela_vendas.loc[linhas, colunas]

tabela_loja = tabela_vendas.loc[tabela_vendas["ID Loja"] == loja , ["ID Loja", "Quantidade", "Valor Final"] ]
display(tabela_loja)

               ID Loja  Quantidade  Valor Final
62      Rio Mar Recife           1          100
63      Rio Mar Recife           2          380
64      Rio Mar Recife           1          200
113     Rio Mar Recife           1          113
142     Rio Mar Recife           3          348
...                ...         ...          ...
100858  Rio Mar Recife           2          550
100859  Rio Mar Recife           3          315
100860  Rio Mar Recife           3          798
100929  Rio Mar Recife           3          180
100930  Rio Mar Recife           3          807

[4099 rows x 3 columns]

In [18]:
tabela_loja = tabela_loja.groupby("ID Loja").sum()
display(tabela_loja)

                Quantidade  Valor Final
ID Loja
Rio Mar Recife        8863      1722766

*Criando uma nova coluna calculada*

In [19]:
tabela_loja["Ticket medio"] = tabela_loja["Valor Final"] / tabela_loja["Quantidade"]
display(tabela_loja)

                Quantidade  Valor Final  Ticket medio
ID Loja
Rio Mar Recife        8863      1722766    194.377299

*enviar email*

In [ ]:
enviar_email(loja, tabela_loja)

**Passo 6: Enviar email para cada loja de cada vez, utilizando o for**

In [ ]:
lista_lojas = tabela.vendas["ID Loja"].unique()

for loja in lista_lojas:
  tabela_loja = tabela_vendas.loc[tabela_vendas["ID Loja"] == loja , ["ID Loja", "Quantidade", "Valor Final"] ]
  tabela_loja = tabela_loja.groupby("ID Loja").sum()
  tabela_loja["Ticket medio"] = tabela_loja["Valor Final"] / tabela_loja["Quantidade"]
  enviar_email(loja, tabela_loja)

In [23]:
lista_lojas = tabela_vendas["ID Loja"].unique()
print(lista_lojas)
# lista com nome de todas as lojas da tabela, sem repetição

['Iguatemi Esplanada' 'Norte Shopping' 'Rio Mar Shopping Fortaleza'
 'Shopping Barra' 'Shopping Ibirapuera' 'Iguatemi Campinas'
 'Shopping Center Leste Aricanduva' 'Passei das Águas Shopping'
 'Shopping Recife' 'Shopping Midway Mall' 'Bourbon Shopping SP'
 'Shopping Center Interlagos' 'Parque Dom Pedro Shopping'
 'Center Shopping Uberlândia' 'Shopping União de Osasco'
 'Shopping Eldorado' 'Shopping Vila Velha' 'Novo Shopping Ribeirão Preto'
 'Rio Mar Recife' 'Palladium Shopping Curitiba' 'Shopping SP Market'
 'Ribeirão Shopping' 'Shopping Iguatemi Fortaleza' 'Shopping Morumbi'
 'Salvador Shopping']